from fastapi import APIRouter
from app.api.v1 import canvas, node, edge, tasks, ws, agent, asset, snapshot, auth, credit, user, recharge, announcement, admin, payment, callback, enhanced, skill_conversation, preset

api_router = APIRouter()
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(user.router)
api_router.include_router(canvas.router)
api_router.include_router(node.router)
api_router.include_router(edge.router)
api_router.include_router(tasks.router)
api_router.include_router(ws.router)
api_router.include_router(agent.router)
api_router.include_router(asset.router)
api_router.include_router(snapshot.router)
api_router.include_router(credit.router)
api_router.include_router(recharge.router)
api_router.include_router(announcement.router)
api_router.include_router(admin.router)
api_router.include_router(payment.router)
api_router.include_router(callback.router)
api_router.include_router(enhanced.router)
api_router.include_router(skill_conversation.router)
api_router.include_router(preset.router)
